### ISSUE TITLE
[BUG] Woofy crashes if the file it's trying to save has an invalid character in it's name

### ISSUE THREAD

**Issue by Snaid1** [vladiliescu/woofy#3]
Bug Description:
I have a def file I just created that, when added to Woofy 1.25, causes it to crash. I'm pretty sure it's because the file name of the file has a Semi-colon : in the file name (which is not allowed in windows), causing the IO stream to fail, and therefore Woofy crashes. 

Desired Behavior:
While ultimately up to you, I'd recommend having Woofy replace illegal characters with an Underscore _ thereby allowing it to continue processing instead of crashing.
Alternatively you could add some sort of option for custom file names.

Additional Information:
Once it crashes it continues to crash on startup due to the comic being in the list still. To get Woofy working for the other comics again I had to go into the Comics.json file and remove the entry for the problematic comic (Mala Tinta in this case). 

Error.txt content:
08/01/2020 23:36:44 System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Woofy.Core.SystemProxies.FileProxy.Move(String sourceFileName, String destFileName)
   at Woofy.Core.Engine.Expressions.DownloadExpression.Download(IEnumerable`1 links, Context context)
   at Woofy.Core.Engine.Expressions.DownloadExpression.Invoke(Object argument, Context context)
   at _MalaTinta.RunImpl(Context context) in C:\Users\Home\AppData\Roaming\Woofy\bin\MalaTinta:line 5
   at Woofy.Core.Engine.Definition.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 

Comic Log File:
[8/1/2020 11:36:43 PM][MalaTinta visit] starting at http://malatinta.com/0000/
[8/1/2020 11:36:44 PM][MalaTinta download] found 1 images
[8/1/2020 11:36:44 PM][MalaTinta download] downloading http://malatinta.com/strips/.0000QW4gaW50/00:00 to C:\Users\Home\Documents\My Comics\MalaTinta\0001_00:00

I attached a zip file containing the def file that reproduces the error as well as the logs quoted above.
[MalaTinta Error.zip](https://github.com/vladiliescu/woofy/files/5011696/MalaTinta.Error.zip)

Please let me know if there is anything I can do to help/any information I can get you.

If I get some time in the next few days I may try to figure out how to fix it myself if you don't by then, but I'm not as familiar with the code as you are so it will take me longer to find where in the code the fix needs to go.

**Comment by Snaid1** [comment]
I had some free time this morning I didn't expect so I submitted a pull request to fix the issue.

**Comment by Snaid1** [comment]
Bug #5 isn't directly related to this bug, but I don't currently have a way to reproduce it except with the comic that hit this issue first.
